/**
 * AUTO-GENERATED by src/scripts/generate-component-audit.mjs — 수동 편집 금지.
 * 재생성: npm run generate:audit
 *
 * P2-H6 컴포넌트 감사 레지스트리: 24개 컴포넌트.
 */

export type ComponentType = 'Page' | 'Modal' | 'Panel' | 'Widget';

export interface ComponentAuditEntry {
  name: string;
  path: string;
  type: ComponentType;
  props: string[];
  emits: string[];
  dependencies: string[];
}

export const COMPONENT_AUDIT: ComponentAuditEntry[] = [
  {
    name: "AgentCommandPanel",
    path: "./AgentCommandPanel.vue",
    type: "Panel",
    props: ["agents","maxHistorySize"],
    emits: [],
    dependencies: [],
  },
  {
    name: "AgentDashboard",
    path: "./AgentDashboard.vue",
    type: "Page",
    props: [],
    emits: [],
    dependencies: [],
  },
  {
    name: "AgentStatusMonitor",
    path: "./AgentStatusMonitor.vue",
    type: "Page",
    props: [],
    emits: [],
    dependencies: [],
  },
  {
    name: "AnalyticsDashboard",
    path: "./AnalyticsDashboard.vue",
    type: "Page",
    props: [],
    emits: [],
    dependencies: [],
  },
  {
    name: "ConfigurationPanel",
    path: "./ConfigurationPanel.vue",
    type: "Panel",
    props: [],
    emits: [],
    dependencies: [],
  },
  {
    name: "ConstitutionViewer",
    path: "./ConstitutionViewer.vue",
    type: "Page",
    props: [],
    emits: [],
    dependencies: [],
  },
  {
    name: "DiscordSetupWizard",
    path: "./DiscordSetupWizard.vue",
    type: "Modal",
    props: [],
    emits: [],
    dependencies: [],
  },
  {
    name: "KnowledgeGraphVisualizer",
    path: "./KnowledgeGraphVisualizer.vue",
    type: "Page",
    props: ["nodes","edges"],
    emits: [],
    dependencies: ["cytoscape","cytoscape-cose-bilkent"],
  },
  {
    name: "LLMDashboard",
    path: "./LLMDashboard.vue",
    type: "Page",
    props: [],
    emits: [],
    dependencies: ["./LLMTab.vue"],
  },
  {
    name: "LLMTab",
    path: "./LLMTab.vue",
    type: "Widget",
    props: ["llm"],
    emits: ["input-sent","response-received","toggle-browser"],
    dependencies: [],
  },
  {
    name: "LogViewer",
    path: "./LogViewer.vue",
    type: "Page",
    props: [],
    emits: [],
    dependencies: [],
  },
  {
    name: "NotificationCenter",
    path: "./NotificationCenter.vue",
    type: "Modal",
    props: [],
    emits: [],
    dependencies: [],
  },
  {
    name: "OllamaModelDownloader",
    path: "./OllamaModelDownloader.vue",
    type: "Widget",
    props: [],
    emits: [],
    dependencies: [],
  },
  {
    name: "OllamaModelManager",
    path: "./OllamaModelManager.vue",
    type: "Widget",
    props: [],
    emits: [],
    dependencies: [],
  },
  {
    name: "PerformanceMonitor",
    path: "./PerformanceMonitor.vue",
    type: "Page",
    props: [],
    emits: [],
    dependencies: [],
  },
  {
    name: "RealTimeDashboard",
    path: "./RealTimeDashboard.vue",
    type: "Page",
    props: [],
    emits: [],
    dependencies: [],
  },
  {
    name: "ReportLoader",
    path: "./ReportLoader.vue",
    type: "Widget",
    props: [],
    emits: [],
    dependencies: [],
  },
  {
    name: "SearchInterface",
    path: "./SearchInterface.vue",
    type: "Widget",
    props: [],
    emits: [],
    dependencies: [],
  },
  {
    name: "SpeechRecognitionPanel",
    path: "./SpeechRecognitionPanel.vue",
    type: "Panel",
    props: [],
    emits: [],
    dependencies: [],
  },
  {
    name: "StatusDashboard",
    path: "./StatusDashboard.vue",
    type: "Page",
    props: [],
    emits: [],
    dependencies: [],
  },
  {
    name: "SystemHealthMonitor",
    path: "./SystemHealthMonitor.vue",
    type: "Page",
    props: [],
    emits: [],
    dependencies: [],
  },
  {
    name: "SystemMetricsGraphs",
    path: "./SystemMetricsGraphs.vue",
    type: "Widget",
    props: [],
    emits: [],
    dependencies: [],
  },
  {
    name: "TaskCreationForm",
    path: "./TaskCreationForm.vue",
    type: "Widget",
    props: [],
    emits: ["task-created","cancel"],
    dependencies: [],
  },
  {
    name: "WebSocketBridge",
    path: "./WebSocketBridge.vue",
    type: "Widget",
    props: [],
    emits: [],
    dependencies: [],
  },
];

export const COMPONENT_AUDIT_COUNT = 24;

// 시각(時刻)에 존재하고, 시간(時間)에 소멸한다.
// Exists in the Moment, Vanishes in Time.
